# Generated by Django 5.2.3 on 2026-01-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('selected_font', models.CharField(default='Bickham Script Pro Regular', max_length=255)),
                ('font_size', models.IntegerField(default=48)),
                ('font_weight', models.CharField(default='400', max_length=50)),
                ('text_color', models.CharField(default='#000000', max_length=50)),
                ('text_x', models.IntegerField(default=0)),
                ('text_y', models.IntegerField(default=0)),
                ('anchor_mode', models.CharField(default='center', max_length=50)),
            ],
        ),
    ]
