# Generated by Django 4.2.29 on 2026-03-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificatePreset',
        ),
    ]
