# Generated by Django 4.2.29 on 2026-04-20 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('text', models.TextField()),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('font', models.TextField(default='Bickham Script Pro Regular')),
                ('font_size', models.IntegerField(default=0)),
                ('font_weight', models.IntegerField(default=0)),
                ('color', models.TextField(default='#000000')),
                ('anchor_mode', models.TextField(choices=[('center', 'Center'), ('left', 'Left')], default='center')),
                ('required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.templates')),
            ],
        ),
    ]
