# Generated by Django 4.2.29 on 2026-04-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
