# Generated by Django 4.2.29 on 2026-04-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_templates_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='collection_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templates',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
