# Generated by Django 4.2.29 on 2026-04-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_templates_collection_id_templates_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='state',
            field=models.TextField(default='active'),
        ),
    ]
