# Generated by Django 4.2.29 on 2026-04-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_templateparams_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateparams',
            name='font_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='templateparams',
            name='label',
            field=models.TextField(default='Participant Name'),
        ),
        migrations.AlterField(
            model_name='templateparams',
            name='text',
            field=models.TextField(default='John Doe'),
        ),
    ]
