# Generated by Django 4.2.30 on 2026-07-31 22:21

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_collections_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(default=app.models._generate_verification_code, max_length=6)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=app.models._default_expiry)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.templates')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='app.templates')),
            ],
            options={
                'indexes': [models.Index(fields=['template', 'email'], name='recipient_template_email_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='publishedrecipient',
            constraint=models.UniqueConstraint(fields=('template', 'email'), name='unique_recipient_per_template'),
        ),
    ]
