# Generated by Django 4.2.30 on 2026-08-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_recipientverification_publishedrecipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='generation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
