# Generated by Django 4.2.30 on 2026-07-31 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_templateparams_font_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='templateparams',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='templates',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='templateparams',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collections',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='collections',
            name='state',
            field=models.CharField(db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='templateparams',
            name='anchor_mode',
            field=models.CharField(choices=[('center', 'Center'), ('left', 'Left')], default='center', max_length=10),
        ),
        migrations.AlterField(
            model_name='templateparams',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='templateparams',
            name='font',
            field=models.CharField(default='Bickham Script Pro Regular', max_length=255),
        ),
        migrations.AlterField(
            model_name='templateparams',
            name='font_weight',
            field=models.CharField(default='400', max_length=10),
        ),
        migrations.AlterField(
            model_name='templateparams',
            name='label',
            field=models.CharField(default='Participant Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='templateparams',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='app.templates'),
        ),
        migrations.AlterField(
            model_name='templateparams',
            name='text',
            field=models.CharField(default='John Doe', max_length=500),
        ),
        migrations.AlterField(
            model_name='templates',
            name='collection_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='templates',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='templates',
            name='state',
            field=models.CharField(db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='templates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='templates',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='collections',
            index=models.Index(fields=['user', 'state'], name='collection_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='templates',
            index=models.Index(fields=['user', 'state'], name='template_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='templates',
            index=models.Index(fields=['user', 'state', 'collection_id'], name='template_user_state_col_idx'),
        ),
    ]
