# Generated by Django 4.2.30 on 2026-08-01 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_templates_generation_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('self_serve', 'Self-Serve'), ('batch', 'Batch')], max_length=20)),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.templates')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template', 'created_at'], name='genevent_template_created_idx')],
            },
        ),
    ]
