# Generated by Django 4.2.30 on 2026-08-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_generationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationevent',
            name='kind',
            field=models.CharField(choices=[('editor', 'Editor'), ('self_serve', 'Self-Serve'), ('batch', 'Batch')], max_length=20),
        ),
    ]
