# Generated by Django 4.2.30 on 2026-08-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='draft_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
