# Generated by Django 4.2.30 on 2026-08-07 06:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_templates_draft_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('password_reset', 'Password Reset')], max_length=20)),
                ('code', models.CharField(default=app.models._generate_verification_code, max_length=6)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=app.models._default_expiry)),
            ],
        ),
    ]
