import csv
import os
import shutil

import gspread
import pandas as pd
from dotenv import load_dotenv
from google.oauth2.service_account import Credentials
from PIL import Image, ImageDraw, ImageFont

load_dotenv()


# Load cert_template
cert_template = None

# Font
font = ImageFont.truetype("arialbd.ttf", 40)

# Ensure output folder exists
os.makedirs("certificates", exist_ok=True)

SHEET_ID = os.getenv("SHEET_ID")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

positions = {1: "Champion", 2: "Runner-Up", 3: "2nd-Runner-Up"}
comps = {
    "CC": "Cyber_City",
    "BoT": "Battle_of_Tribes",
    "GF": "Geometric_Forest",
    "SA": "Skyline_Adventures",
}


# Tests was generated by Co-pilot
def validate_requirements():
    """
    Validate that all required files and configurations exist before processing.
    Returns tuple: (is_valid: bool, error_messages: list)
    """
    errors = []

    # Check environment variables
    if not SHEET_ID:
        errors.append("SHEET_ID environment variable is not set")
    if not GOOGLE_API_KEY:
        errors.append("GOOGLE_API_KEY environment variable is not set")

    # Check service account file
    service_account_file = "./service_account.json"
    if not os.path.exists(service_account_file):
        errors.append(f"Service account file not found: {service_account_file}")

    # Check font file
    font_file = "arialbd.ttf"
    if not os.path.exists(font_file):
        errors.append(f"Font file not found: {font_file}")

    # Check templates directory structure
    templates_dir = "templates"
    if not os.path.exists(templates_dir):
        errors.append(f"Templates directory not found: {templates_dir}")
    else:
        # Check each competition template
        for comp_code, comp_name in comps.items():
            comp_dir = os.path.join(templates_dir, comp_name)
            if not os.path.exists(comp_dir):
                errors.append(f"Competition template directory not found: {comp_dir}")
                continue

            # Check position templates
            for pos_num, position in positions.items():
                position_formatted = position.replace("-", "_")
                template_file = os.path.join(
                    comp_dir, f"{comp_name}_{position_formatted}.png"
                )
                if not os.path.exists(template_file):
                    errors.append(f"Template file not found: {template_file}")

    return len(errors) == 0, errors


# Tests was generated by Co-pilot
def validate_csv_data(csv_file="results.csv"):
    """
    Validate the CSV data has all required fields and proper data.
    Returns tuple: (is_valid: bool, error_messages: list)
    """
    errors = []

    if not os.path.exists(csv_file):
        errors.append(f"CSV file not found: {csv_file}")
        return False, errors

    try:
        df = pd.read_csv(csv_file)
    except Exception as e:
        errors.append(f"Error reading CSV file: {str(e)}")
        return False, errors

    # Check required columns
    required_columns = [
        "Competition",
        "Team",
        "Coach",
        "Organisation",
        "Player",
        "Position",
    ]
    missing_columns = [col for col in required_columns if col not in df.columns]
    if missing_columns:
        errors.append(f"Missing required columns in CSV: {missing_columns}")

    if len(df) == 0:
        errors.append("CSV file is empty")
        return False, errors

    # Check for empty/null values in critical fields
    for row_index, (_, row) in enumerate(df.iterrows()):
        row_num = (
            row_index + 2
        )  # +2 because: +1 for 1-based indexing, +1 for header row
        row_errors = []

        # Check each required field
        if pd.isna(row["Competition"]) or str(row["Competition"]).strip() == "":
            row_errors.append("Competition")
        if pd.isna(row["Team"]) or str(row["Team"]).strip() == "":
            row_errors.append("Team")
        if pd.isna(row["Coach"]) or str(row["Coach"]).strip() == "":
            row_errors.append("Coach")
        if pd.isna(row["Organisation"]) or str(row["Organisation"]).strip() == "":
            row_errors.append("Organisation")
        if pd.isna(row["Player"]) or str(row["Player"]).strip() == "":
            row_errors.append("Player")
        if pd.isna(row["Position"]) or str(row["Position"]).strip() == "":
            row_errors.append("Position")

        if row_errors:
            errors.append(f"Row {row_num}: Missing or empty fields: {row_errors}")

        # Validate competition exists in our mapping
        comp_name = str(row["Competition"]).replace(" ", "_")
        if comp_name not in comps.values():
            errors.append(
                f"Row {row_num}: Invalid competition '{row['Competition']}'. Valid competitions: {list(comps.values())}"
            )

        # Validate position
        position = str(row["Position"])
        if position not in positions.values():
            errors.append(
                f"Row {row_num}: Invalid position '{position}'. Valid positions: {list(positions.values())}"
            )

    return len(errors) == 0, errors


def read(comp_id):
    SERVICE_ACCOUNT_FILE = "./service_account.json"
    SCOPES = ["https://www.googleapis.com/auth/spreadsheets.readonly"]
    creds = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
    client = gspread.authorize(creds)

    spreadsheet = client.open_by_url(
        f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/edit"
    )
    comp_name = comps[comp_id].replace("_", " ")
    worksheet = spreadsheet.worksheet(comp_name)

    # Get data
    data = worksheet.get_all_values()

    # Sort all rows (skip header)
    content_sorted = sorted(data[1:], key=lambda x: int(x[4]), reverse=True)

    # Top 3 teams
    top_three = content_sorted[:3]

    with open("results.csv", "w", newline="\n") as file:
        writer = csv.writer(file)
        writer.writerow(
            ["Competition", "Team", "Coach", "Organisation", "Player", "Position"]
        )

        for rank, row in enumerate(top_three, start=1):
            team = row[0]
            coach = row[3]
            players = row[5]
            position = positions[rank]

            for player in players.split(","):
                comp_name = comps[comp_id].replace("_", " ")
                writer.writerow(
                    [comp_name, team, coach, "School", player.strip(), position]
                )

    print(top_three)
    return True


def generate_cert(column):
    # Validate requirements before starting
    is_valid, errors = validate_requirements()
    if not is_valid:
        print("❌ Validation failed! Cannot generate certificates:")
        for error in errors:
            print(f"  - {error}")
        return False

    # Validate CSV data
    csv_valid, csv_errors = validate_csv_data("results.csv")
    if not csv_valid:
        print("❌ CSV validation failed! Cannot generate certificates:")
        for error in csv_errors:
            print(f"  - {error}")
        return False

    print("✅ All validations passed! Starting certificate generation...")

    if os.path.exists("certificates"):
        shutil.rmtree("certificates")
    else:
        os.makedirs("certificates", exist_ok=True)

    successful_certs = 0
    failed_certs = 0

    for _, row in column.iterrows():
        try:
            position = row["Position"].replace("-", "_")
            comp = row["Competition"].replace(" ", "_")

            # Additional validation for this specific row
            template_path = f"templates/{comp}/{comp}_{position}.png"
            if not os.path.exists(template_path):
                print(f"❌ Template not found for {comp} {position}: {template_path}")
                failed_certs += 1
                continue

            cert_template = Image.open(template_path)

            team_name = str(row["Team"]).strip()
            player_name = str(row["Player"]).strip()
            coach = str(row["Coach"]).strip()
            org = str(row["Organisation"]).strip()

            # Validate all fields are non-empty after processing
            if not all([team_name, player_name, coach, org]):
                print(
                    f"❌ Missing required data for {player_name}: team={team_name}, coach={coach}, org={org}"
                )
                failed_certs += 1
                continue

            img = cert_template.copy()
            draw = ImageDraw.Draw(img)

            team_org_y = 935
            team_player_x = 430
            org_coach_x = 1570
            player_coach_y = 1005

            print(f"📝 Generating certificate for: {player_name} ({comp} {position})")

            # Team
            draw.text((team_player_x, team_org_y), team_name, fill="black", font=font)

            # Player
            draw.text(
                (team_player_x, player_coach_y), player_name, fill="black", font=font
            )

            # Organization
            draw.text((org_coach_x, team_org_y), org, fill="black", font=font)

            # Coach
            draw.text((1500, player_coach_y), coach, fill="black", font=font)

            cert_dir = f"certificates/{comp}/{position}"
            os.makedirs(cert_dir, exist_ok=True)

            # Sanitize filename
            safe_filename = "".join(
                c for c in player_name if c.isalnum() or c in (" ", "-", "_")
            ).rstrip()
            if not safe_filename:
                safe_filename = f"certificate_{successful_certs + 1}"

            output_path = f"{cert_dir}/{safe_filename}.png"
            img.save(output_path)

            print(f"✅ Saved certificate: {output_path}")
            successful_certs += 1

        except Exception as e:
            print(
                f"❌ Error generating certificate for {row.get('Player', 'Unknown')}: {str(e)}"
            )
            failed_certs += 1
            continue

    print("\n📊 Certificate Generation Summary:")
    print(f"  ✅ Successful: {successful_certs}")
    print(f"  ❌ Failed: {failed_certs}")
    print(f"  📁 Total: {successful_certs + failed_certs}")

    return successful_certs > 0


def main():
    print("🚀 Starting ENJOYAI Certificate Generation System...")

    # Run initial validation
    is_valid, errors = validate_requirements()
    if not is_valid:
        print("❌ Initial validation failed:")
        for error in errors:
            print(f"  - {error}")
        print(
            "\n💡 Please fix the above issues before running the certificate generator."
        )
        return False

    done = read("CC")
    if done:
        # try:
        names = pd.read_csv("results.csv")
        # except File

        success = generate_cert(names)
        if success:
            print("\n🎉 Certificate generation completed successfully!")
        else:
            print("\n❌ Certificate generation failed. Check the errors above.")
        return success
    else:
        print("❌ Failed to read data from Google Sheets.")
        return False


if __name__ == "__main__":
    main()
