import csv
import mimetypes
import os
import shutil
import smtplib
from email.message import EmailMessage

import gspread
import pandas as pd
from dotenv import load_dotenv
from google.oauth2.service_account import Credentials
from PIL import Image, ImageDraw, ImageFont


def png_to_pdf(png_path, output_path=None):
    if not os.path.exists(png_path):
        raise FileNotFoundError(f"File not found: {png_path}")

    # Open image
    image = Image.open(png_path).convert("RGB")

    # Default output path = same name but .pdf
    if output_path is None:
        output_path = os.path.splitext(png_path)[0] + ".pdf"

    # Save as PDF
    image.save(output_path, "PDF", resolution=100.0)
    return output_path


load_dotenv()

smtp_server = "smtp.gmail.com"  # e.g., 'smtp.gmail.com' for Gmail
port = 465  # or 465 for SSL
username = os.getenv("EMAIL")
password = os.getenv("PASSWORD")  # Use an app password for services like Gmail


def sendEmail(to_email, name, attachment_paths=None, use_ssl=True):
    msg = EmailMessage()
    msg["Subject"] = "Enjoy AI Volunteer Certification"
    msg["From"] = "info@makersplacegh.com"
    msg["To"] = to_email
    msg.set_content(
        f"Dear {name},\n\n"
        "We sincerely appreciate the time, energy, and dedication you contributed as a volunteer. "
        "Your support played a vital role in making this event a true success.\n\n"
        "As a token of our gratitude, please find your certificate of appreciation attached. "
        "We are grateful to have had you on our team and hope to work together again in the future.\n\n"
        "With appreciation,\n"
        "\n"
        "Enjoy AI"
    )

    if attachment_paths:
        for attachment_path in attachment_paths:
            if attachment_path and os.path.exists(attachment_path):
                with open(attachment_path, "rb") as f:
                    file_data = f.read()
                    file_name = os.path.basename(attachment_path)

                mime_type, _ = mimetypes.guess_type(attachment_path)
                if mime_type is None:
                    mime_type = "application/octet-stream"
                maintype, subtype = mime_type.split("/", 1)

                msg.add_attachment(
                    file_data, maintype=maintype, subtype=subtype, filename=file_name
                )

    try:
        if username and password:
            if use_ssl:
                with smtplib.SMTP_SSL(smtp_server, 465) as server:
                    server.login(username, password)
                    server.send_message(msg)
            else:
                with smtplib.SMTP(smtp_server, 587) as server:
                    server.ehlo()
                    server.starttls()
                    server.ehlo()
                    server.login(username, password)
                    server.send_message(msg)

            print(f"✅ Email sent to {to_email}")
            return True
    except Exception as e:
        print(f"❌ Failed to send email to {to_email}: {str(e)}")
        return False


# # Load cert_template
cert_template = Image.open("template.jpg")
cert_dir = "certificates/"

# Font
font = ImageFont.truetype("BickhamScriptProRegular.ttf", 280)

# Ensure output folder exists
os.makedirs("certificates", exist_ok=True)


# Tests was generated by Co-pilot
def validate_csv_data(csv_file="names.csv"):
    """
    Validate the CSV data has all required fields and proper data.
    Returns tuple: (is_valid: bool, error_messages: list)
    """
    errors = []

    if not os.path.exists(csv_file):
        errors.append(f"CSV file not found: {csv_file}")
        return False, errors

    try:
        df = pd.read_csv(csv_file)
    except Exception as e:
        errors.append(f"Error reading CSV file: {str(e)}")
        return False, errors

    # Check required columns
    required_columns = ["Name", "Email"]
    missing_columns = [col for col in required_columns if col not in df.columns]
    if missing_columns:
        errors.append(f"Missing required columns in CSV: {missing_columns}")

    if len(df) == 0:
        errors.append("CSV file is empty")
        return False, errors

    # Check for empty/null values in critical fields
    for row_index, (_, row) in enumerate(df.iterrows()):
        row_num = (
            row_index + 2
        )  # +2 because: +1 for 1-based indexing, +1 for header row
        row_errors = []

        # Check each required field
        if pd.isna(row["Name"]) or str(row["Name"]).strip() == "":
            row_errors.append("Name")
        if pd.isna(row["Email"]) or str(row["Email"]).strip() == "":
            row_errors.append("Email")

        if row_errors:
            errors.append(f"Row {row_num}: Missing or empty fields: {row_errors}")

    return len(errors) == 0, errors


SHEET_ID = os.getenv("VOLUNTEERS_SHEET_ID")

msg = EmailMessage()


def read_from_worksheet():
    SERVICE_ACCOUNT_FILE = "./service_account.json"
    SCOPES = ["https://www.googleapis.com/auth/spreadsheets.readonly"]
    creds = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
    client = gspread.authorize(creds)

    spreadsheet = client.open_by_url(
        f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/edit"
    )
    worksheet = spreadsheet.worksheet("Responses")

    # Get data
    data = worksheet.get_all_values()
    data = data[1:]

    with open("names.csv", "w", newline="\n") as file:
        writer = csv.writer(file)
        writer.writerow(["Name", "Email"])

        for row in data:
            writer.writerow([row[1], row[2]])

    return True


def generate_cert(column):
    # Validate CSV data
    csv_valid, csv_errors = validate_csv_data("names.csv")
    if not csv_valid:
        print("❌ CSV validation failed! Cannot generate certificates:")
        for error in csv_errors:
            print(f"  - {error}")
        return False

    print("✅ All validations passed! Starting certificate generation...")

    if os.path.exists("certificates"):
        shutil.rmtree("certificates")
    else:
        os.makedirs("certificates", exist_ok=True)

    successful_certs = 0
    failed_certs = 0

    for _, row in column.iterrows():
        try:
            name = str(row["Name"]).strip()
            email = str(row["Email"]).strip()

            img = cert_template.copy()
            draw = ImageDraw.Draw(img)

            print(f"📝 Generating certificate for: {name}")

            bbox = draw.textbbox((0, 0), name, font=font)
            text_width = bbox[2] - bbox[0]
            image_width = img.width
            x = (image_width - text_width) // 2
            y = 1200 - 80
            draw.text((0, -90), name, fill="#4B4B4B", font=font)
            os.makedirs(cert_dir, exist_ok=True)

            # Sanitize filename
            safe_filename = "".join(
                c for c in name if c.isalnum() or c in (" ", "-", "_")
            ).rstrip()
            if not safe_filename:
                safe_filename = f"certificate_{successful_certs + 1}"

            output_path = f"{cert_dir}/{safe_filename}.png"
            img.save(output_path)

            # png_to_pdf(f"certificates/{name}.png", f"certificates/{name}.pdf")

            # sendEmail(
            #     email,
            #     name,
            #     attachment_paths=[
            #         f"certificates/{name}.png",
            #         f"certificates/{name}.pdf",
            #     ],
            # )

            print(f"✅ Saved certificate: {output_path}")
            successful_certs += 1

        except Exception as e:
            print(
                f"❌ Error generating certificate for {row.get('Player', 'Unknown')}: {str(e)}"
            )
            failed_certs += 1
            continue

    print("\n📊 Certificate Generation Summary:")
    print(f"  ✅ Successful: {successful_certs}")
    print(f"  ❌ Failed: {failed_certs}")
    print(f"  📁 Total: {successful_certs + failed_certs}")

    return successful_certs > 0


def main():
    print("🚀 Starting Certificate Generation System...")

    # if read_from_worksheet():
    names = pd.read_csv("names.csv")
    success = generate_cert(names)
    if success:
        print("\n🎉 Certificate generation completed successfully!")
    else:
        print("\n❌ Certificate generation failed. Check the errors above.")


if __name__ == "__main__":
    main()
